{"name": "test_api_audit[case7]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0", "trace": "self = <tests.test_audit.Test_Audit object at 0x00000204E60FC550>\ncase = {'Headers': '{\"Content-Type\":\"application/json\",\"X-Lemonban-Media-Type\":\"lemonban.v2\",\"Authorization\":None}', 'auto_sc..._not只能为true或者false', 'case_id': 8, 'data': '{\\n    \"loan_id\":\"#project_id4#\",\\n    \"approved_or_not\":\"审核通过\"\\n\\n}', ...}\nget_root_token = ({'N_id': 2064912, 'get_id': 2037397, 'give_id': 2052534, 'no_id': 2037790, ...}, {'shenhe': 'Bearer eyJhbGciOiJIUzUxM...2OH0.1GgaFWZ71OaRQ88ag6W2odW9WgeK2Ve3aNUDnPnOv-J7EqPD0qdqmTgaRheGlQGypDhBtBPWbzebLPiIJt37dA', 'shenhe_id': 1000337288})\nget_token = ('Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEwMDAzMzcyNjUsImV4cCI6MTYxOTQxODQ2OH0.H5s8pSRMZRQcs8mpZV0q7WfT4F-RBDY3F4XqTuTg4E25MqYIZOZJZKSaEcSKGnuCTFxzvXD0DOw7WeUGAST67Q', 1000337265)\n\n    @pytest.mark.parametrize(\"case\",cases)\n    def test_api_audit(self,case,get_root_token,get_token):\n        data = self.mid_case.re_repelace(case[\"data\"], 1)\n        excepted = case[\"excepted\"]\n        head = eval(case[\"Headers\"])\n        if head[\"Authorization\"]:\n            head[\"Authorization\"] =  get_token[0]\n        else:\n            head[\"Authorization\"] = get_root_token[1][\"shenhe\"]\n        if case[\"case_id\"] == 3:\n            respose =  self.mid_obj.req_obj.send_request(method=case[\"method\"], url=self.url, data=data, headers=head)\n        else:\n            data = eval(data)\n            respose = self.mid_obj.req_obj.send_request(method=case[\"method\"], url=self.url, json=data, headers=head)\n    \n        #断言\n        try:\n            for k,v in eval(case[\"excepted\"]).items():\n                assert jsonpath.jsonpath(respose, k)[0] == v\n            self.mid_obj.logger.info(\"第{}条测试用例通过,请求参数是{}\".format(case[\"case_id\"], data))\n            self.excel.write_data(row=case[\"case_id\"] + 1, column=9, value=\"pass\")\n        except AssertionError as e:\n            Midd_Ware.logger.info(\"第{}条测试用例不通过 ！\\n 请求体是{} 请求内容是{}。预期结果是{}---返回结果是{}\".format(case[\"case_id\"], data, case[\"title\"],excepted,respose[\"msg\"]))\n            self.excel.write_data(row=case[\"case_id\"] + 1, column=9, value=\"failure\")\n>           raise e\n\ntest_audit.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.test_audit.Test_Audit object at 0x00000204E60FC550>\ncase = {'Headers': '{\"Content-Type\":\"application/json\",\"X-Lemonban-Media-Type\":\"lemonban.v2\",\"Authorization\":None}', 'auto_sc..._not只能为true或者false', 'case_id': 8, 'data': '{\\n    \"loan_id\":\"#project_id4#\",\\n    \"approved_or_not\":\"审核通过\"\\n\\n}', ...}\nget_root_token = ({'N_id': 2064912, 'get_id': 2037397, 'give_id': 2052534, 'no_id': 2037790, ...}, {'shenhe': 'Bearer eyJhbGciOiJIUzUxM...2OH0.1GgaFWZ71OaRQ88ag6W2odW9WgeK2Ve3aNUDnPnOv-J7EqPD0qdqmTgaRheGlQGypDhBtBPWbzebLPiIJt37dA', 'shenhe_id': 1000337288})\nget_token = ('Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEwMDAzMzcyNjUsImV4cCI6MTYxOTQxODQ2OH0.H5s8pSRMZRQcs8mpZV0q7WfT4F-RBDY3F4XqTuTg4E25MqYIZOZJZKSaEcSKGnuCTFxzvXD0DOw7WeUGAST67Q', 1000337265)\n\n    @pytest.mark.parametrize(\"case\",cases)\n    def test_api_audit(self,case,get_root_token,get_token):\n        data = self.mid_case.re_repelace(case[\"data\"], 1)\n        excepted = case[\"excepted\"]\n        head = eval(case[\"Headers\"])\n        if head[\"Authorization\"]:\n            head[\"Authorization\"] =  get_token[0]\n        else:\n            head[\"Authorization\"] = get_root_token[1][\"shenhe\"]\n        if case[\"case_id\"] == 3:\n            respose =  self.mid_obj.req_obj.send_request(method=case[\"method\"], url=self.url, data=data, headers=head)\n        else:\n            data = eval(data)\n            respose = self.mid_obj.req_obj.send_request(method=case[\"method\"], url=self.url, json=data, headers=head)\n    \n        #断言\n        try:\n            for k,v in eval(case[\"excepted\"]).items():\n>               assert jsonpath.jsonpath(respose, k)[0] == v\nE               assert 1 == 0\n\ntest_audit.py:39: AssertionError"}, "attachments": [{"name": "log", "source": "2dab137d-c8db-4b50-b36e-19f27751d22e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a4fac248-e288-4b10-bbbb-e3d960f34e9e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'case_id': 8, 'interface': '审核项目', 'url': '/loan/audit', 'method': 'PATCH', 'title': '审核类型传错误', 'data': '{\\n    \"loan_id\":\"#project_id4#\",\\n    \"approved_or_not\":\"审核通过\"\\n\\n}', 'Headers': '{\"Content-Type\":\"application/json\",\"X-Lemonban-Media-Type\":\"lemonban.v2\",\"Authorization\":None}', 'excepted': '{\"$..code\":0, \"$..msg\": \"项目不在审核中状态\"}', 'result': 'failure', 'auto_script': 'approved_or_not只能为true或者false'}"}], "start": 1619418171379, "stop": 1619418171601, "uuid": "9fe26141-d3db-4064-94d1-b745312f5977", "historyId": "75a61a7b1118c7d552b3cc3d463457db", "testCaseId": "b4fbaf9314ba85c67acc5815b54923c3", "fullName": "test_audit.Test_Audit#test_api_audit", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_audit')"}, {"name": "suite", "value": "test_audit"}, {"name": "subSuite", "value": "Test_Audit"}, {"name": "host", "value": "DESKTOP-AC1MULO"}, {"name": "thread", "value": "12600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_audit"}]}